{% set name = "mgrs" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99e0007d417042009595665c3ef2214bb51b07aefd061071ea101e9bed6b6d01

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - packaging

test:
  requires:
    - pytest
    - pip
  imports:
    - mgrs
  commands:
    - pip check

about:
  home: https://github.com/hobu/mgrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: MGRS coordinate conversion for Python
  dev_url: https://github.com/hobu/mgrs
  doc_url: https://github.com/hobuinc/mgrs/blob/main/README.rst

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - oblute
    - rluria14
