travis:
  secure:
    BINSTAR_TOKEN: ZV/eTFO44dPjAMwRnXjf4seBXTB8FyFz1sqkUfUWJTzC/OALDE0IROy4GHWM4LHI/Q+a+sBs+piPaxsNXsHR+7y8t8L7KSt59ReZmLxaSXb7nlFKqdjlGBjov0HL9QIXQVrlIPA/LO2El5zEr07X4867vVEEkP7dtTFSY5jcS9GCN4seBRTWCqlYwreJ/mHxOg0t3WKuAKLHINa4/c7MFu6VRYNyl/mQ6SzuEhSYHDazCR5vDjqVAYAyC2WTdGjEwl2Vn0EeujH50eUBivFXI9VjPu/L576vGQ/A9l5m1ZuQYcTHyYDqznLQAMFPhbpOBC5m4WTX7jKYHuWZUHoyPE08TYSycwOLkK0lH6dmgGdZBgM1ibfnZeMic/4y0nOS+LBa03Rn6g6wvj39zJdypNZy8nKhAgy/XrtxOZVxfcuGfSPEIcFFBfO7Nn+2HnU2TH5czcECpDVw3z72ui7zG1Ziw9ACmCZrK2LfOknl4wD8Cnul2IUF11k5W6MvVvzYxuEkP7jaCKcU+AXmotXY3Tw6bRx5z8Ik4ZAepu4Zwc6wnJwcLYz+t8q6sQueNSEK+6MjS6D72mId5Z8WiE9I3dgHWTK5ENZ3pUzPIVMQlrATR3z0EXe31CR0roXRJeml/4TOBrzFIqLRx7fzsBjTQOO9CEnT9OeADu4CBRL+Y9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
